version: 2
jobs:
  build:
    docker:
      - image: elixir:1.7-alpine
      - image: postgres:11.1-alpine
        environment:
          POSTGRES_USER: ubuntu
    steps:
      - checkout
      - run: |
          mix local.hex --force &&
          mix local.rebar &&
          mix deps.get &&
          mix ecto.create
      - run: mix test
