version: 2.1
jobs:
  build:
    docker:
      - image: elixir:1.10.3
      - image: postgres:12.3-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - run: |
          mix local.hex --force &&
          mix local.rebar --force
      - restore_cache:  # restores saved mix cache
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:  # list of cache keys, in decreasing specificity
          - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          - v1-mix-cache-{{ .Branch }}
          - v1-mix-cache
      - run: MIX_ENV=test mix deps.get
      - save_cache:  # generate and store mix cache
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - run: MIX_ENV=test mix ecto.create
      - run: mix test
      - store_test_results:
          path: _build/test/lib/kakebosan
